<?php

namespace app\admin\controller;
use app\admin\model\Market as MarketModel;
class Market extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 二级市  列表 
        $this->assign('city_list',Cache('city_list'));
    }
    /*列表*/
    public function index()
    {
        $model = new MarketModel;
        $pagetitle = '市场管理列表';
        $where = [];
        $post = request()->param('post.');
        if(!empty($post['keywords'])){
            $where['name'] = ['like','%'.$post['keywords'].'%'];
        }
        if(!empty($post['city'])){
            $where['room_city'] = $post['city'];
        }
        if(!empty($post['status'])){
            $where['status'] = $post['status'];
        }
        $list =  $model->allList($where,20);
        return $this->fetch('index',['list'=>$list,'pagetitle'=>$pagetitle]);
    }
    /*添加*/
    public function add()
    {
        $this->assign('pagetitle','开通市场');
        if($this->request->isAjax())
        {
            $model = new MarketModel;
            $post = $this->postData();
            $r = $model->add($post);
            if($r){
                $this->add_SystemLog('开通市场', '增加', $post['name']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            return $this->fetch();
        }
    }
/*修改*/
    public function update()
    {
        $this->assign('pagetitle','编辑市场');
        $model = new MarketModel;
        if($this->request->isAjax())
        {
            $post = $this->postData();
            $r = $model->edit($post);
            if($r !== false){
                $this->add_SystemLog('市场', '修改', $post['name']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            $get = $this->getData();
            $info = $model->get($get['id']);
            return $this->fetch('update',['info'=>$info]);
        }
    }
    /*切换状态*/
    public function toggle()
    {
       if(request()->isAjax()){
        $data = request()->get();
        if($data['status'] == 1){
            $msg = '开通';
            $data['start_time'] = time();
        }else{
            $msg = '关闭';
        }
        $model = new MarketModel;
        $r = $model->edit($data);
        if($r){
           return msg_ok(1,$msg.'成功');
        }else{
           return msg_ok(2,$msg.'失败');
        }
       }
    }
    /*删除*/
    // public function destroy()
    // {
    //     $model = new MarketModel;
    //     if($this->request->isAjax())
    //     {
    //         $post = $this->getData();
    //         $info = $model->get($post['id']);
    //         if($post['id'] && $info){
    //             $r = $model->destroy($post['id']);
    //             if($r){
    //                 $this->add_SystemLog('市场', '删除', $info['name']);
    //                 return ['ret'=>200, 'msg'=>'删除成功'];
    //             }
    //         }
    //     }else{
    //         return ['ret'=>401, 'msg'=>'请求错误'];
    //     }
    // }
}