<?php
/**
 * Created by PhpStorm.
 * User: 简配
 * Date: 2018/12/12
 * Time: 11:16
 */

namespace app\admin\controller;
use app\admin\model\CaseHome as CaseHomeModel;
use app\admin\model\CaseType;
use app\admin\model\ProjectType;
use app\admin\model\ServiceType;
use app\admin\model\Users;

class CaseHome extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $c_key = 'mcoa_user_ui_all';
        $c_key2 = 'project_all_q';
        $c_key3 = 'service_all_q';
        if(!GetCache($c_key)){
            $list = Users::where(['isSale'=>1,'position'=>'UI设计'])->order('isJob')->select();
            SetCache($c_key,$list);
        }
        if(!GetCache($c_key2)){
            $list2 = ProjectType::where(['status'=>1])->order('px')->select();
            SetCache($c_key2,$list2);
        }
        if(!GetCache($c_key3)){
            $list3 = ServiceType::where(['status'=>1])->order('px')->select();
            SetCache($c_key3,$list3);
        }
        $cities_list = db('cities')->field('area_code id,area_name name')->cache(true)->select();
        $this->assign('oa_user_ui_list',GetCache($c_key));
        $this->assign('project_list',GetCache($c_key2));
        $this->assign('service_list',GetCache($c_key3));
        $this->assign('cities_list',$cities_list);
    }

    public function index($keywords = '',$page = 1)
    {

        $this->assign('pagetitle','案例列表');
        $model = new CaseHomeModel;
        $where = [];
        if(!empty($keywords))
        {
            $where['title|home_title'] = ['like',"%$keywords%"];
        }
        $field = 'id,title,image,ctime,utime,recommend,type';
        $list = $model->PageList($where,$field,15,$page);
        return $this->fetch('index',['list'=>$list]);
    }
    //添加
    public function add_case()
    {
        $this->assign('pagetitle','添加案例');
        $type_model = new CaseType;
        if($this->request->isAjax())
        {
            $model = new CaseHomeModel;
            $post = $this->postData();
            $post['ctime'] = time();
//            return $post;
            $r = $model->add($post);
            if($r){
                $this->add_SystemLog('案例', '增加', $post['title']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            $case_type_key = 'case_type_list';
            if(!GetCache($case_type_key))
            {
                $case_type =$type_model->where('status',1)->order('px,id')->select();
                SetCache($case_type_key,$case_type);
            }
            $case_type = GetCache($case_type_key);
            $this->assign('case_type',$case_type);
            return $this->fetch();
        }
    }
    //修改
    public function update_case()
    {
        $this->assign('pagetitle','编辑案例类型');
        $model = new CaseHomeModel;
        $type_model = new CaseType;
        if($this->request->isAjax())
        {
            $post = $this->postData();
            $post['utime'] = time();
            $r = $model->edit($post);
            if($r !== false){
                $this->add_SystemLog('案例', '修改', $post['title']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            $get = $this->getData();
            $info = $model->get($get['id']);
            $case_type_key = 'case_type_list';
            if(!GetCache($case_type_key))
            {
                $case_type = $type_model->where('status',1)->order('px,id')->select();
                SetCache($case_type_key,$case_type);
            }
            $case_type = GetCache($case_type_key);
            return $this->fetch('update_case',['info'=>$info,'case_type'=>$case_type]);
        }
    }
    //删除案例
    public function destroy()
    {
        $model = new CaseHomeModel;
        if($this->request->isAjax())
        {
            $post = $this->getData();
            $info = $model->get($post['id']);
            if($post['id'] && $info){
                $r = $model->destroy($post['id']);
                if($r){
                    $this->add_SystemLog('案例类型', '删除', $info['title']);
                    return ['ret'=>200, 'msg'=>'删除成功'];
                }
            }
        }else{

            return ['ret'=>401, 'msg'=>'请求错误'];
        }
    }

    public function case_img_index()
    {
        return $this->fetch();
    }
}