<?php
/**
 * Created by PhpStorm.
 * User: 简配
 * Date: 2018/12/12
 * Time: 14:32
 */

namespace app\admin\controller;
use app\admin\model\CaseType as CaseTypeModel;
class CaseType extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $model = new CaseTypeModel;
        $pagetitle = '案例类型列表';
        $list =  $model->paginate(20,false,['query'=>request()->param()]);
        return $this->fetch('index',['list'=>$list,'pagetitle'=>$pagetitle]);
    }
    public function add_case()
    {
        $this->assign('pagetitle','添加案例类型');
        if($this->request->isAjax())
        {
            $model = new CaseTypeModel;
            $post = $this->postData();
            $post['ctime'] = time();
            $r = $model->add($post);
            if($r){
                $this->add_SystemLog('案例类型', '增加', $post['name']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            return $this->fetch();
        }
    }

    public function update_case()
    {
        $this->assign('pagetitle','编辑案例类型');
        $model = new CaseTypeModel;
        if($this->request->isAjax())
        {
            $post = $this->postData();
            $post['utime'] = time();
            $r = $model->edit($post);
            if($r !== false){
                $this->add_SystemLog('案例类型', '修改', $post['name']);
                return ['ret'=>200, 'msg'=>'操作成功'];
            }
        }else{
            $get = $this->getData();
            $info = $model->get($get['id']);
            return $this->fetch('update_case',['info'=>$info]);
        }
    }

    public function destroy()
    {
        $model = new CaseTypeModel;
        if($this->request->isAjax())
        {
            $post = $this->getData();
            $info = $model->get($post['id']);
            if($post['id'] && $info){
                $r = $model->destroy($post['id']);
                if($r){
                    $this->add_SystemLog('案例类型', '删除', $info['name']);
                    return ['ret'=>200, 'msg'=>'删除成功'];
                }
            }
        }else{

            return ['ret'=>401, 'msg'=>'请求错误'];
        }
    }
}